version: '3.8'

services:
  # Backend API Service (Express)
  backend:
    # IMPORTANT: Replace 'your-dockerhub-username' with your actual Docker Hub username.
    image: zephylarius/blog-backend:latest
    container_name: blog-backend
    restart: unless-stopped
    environment:
      - PORT=5000
    networks:
      - blog-network
    # The healthcheck is not strictly needed here since depends_on handles startup order,
    # but it can be useful for monitoring.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Service (React + Nginx)
  frontend:
    # IMPORTANT: Replace 'your-dockerhub-username' with your actual Docker Hub username.
    image: zephylarius/blog-frontend:latest
    container_name: blog-frontend
    restart: unless-stopped
    ports:
      - "80:80" # Map host port 80 to container port 80
    networks:
      - blog-network
    depends_on:
      # This ensures the backend is running and healthy before the frontend starts.
      # Note: This depends_on syntax requires Docker Compose version 2.1+
      backend:
        condition: service_healthy

networks:
  blog-network:
    driver: bridge
