version: '3.8'

services:
  # Backend API Service (Express)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blog-backend
    restart: unless-stopped
    environment:
      - PORT=5000
    networks:
      - blog-network
    healthcheck:
      # Use curl to check if the health endpoint is responding correctly
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 15s
      timeout: 10s
      retries: 5

  # Frontend Service (React + Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: blog-frontend
    restart: unless-stopped
    ports:
      - "80:80" # Map host port 80 to container port 80
    networks:
      - blog-network
    depends_on:
      backend:
        condition: service_healthy

networks:
  blog-network:
    driver: bridge