# Name of the workflow
name: CI - Build and Push Docker Images

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build-and-push"
  build-and-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx for more advanced build capabilities
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      # You will need to create a DOCKERHUB_USERNAME secret and a DOCKERHUB_TOKEN secret in your repository settings
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Build and push the backend image
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend # Path to the backend Dockerfile
          file: ./backend/Dockerfile
          push: true # Actually push the image to the registry
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blog-backend:latest

      # Step 5: Build and push the frontend image
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend # Path to the frontend Dockerfile
          file: ./frontend/Dockerfile
          push: true # Actually push the image to the registry
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blog-frontend:latest